spring:
  application.name: cinemarest
  profiles.active: development
  main:
    web-environment: true

---

spring:
  profiles: development

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: MySQLDialect


---

spring:
  profiles: test

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinemaTest
    username: root
    password:

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: MySQLDialect